# Generated by Django 2.0.1 on 2018-09-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appcasestep',
            old_name='Appcase',
            new_name='appcase',
        ),
    ]
