# Generated by Django 2.0.1 on 2018-10-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20180923_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='apitester',
            field=models.CharField(max_length=16, null=True, verbose_name='测试负责人'),
        ),
    ]
